%% Create Graphs
 
%%%%%%%%%%%%%%%%%%%graph 1%%%%%%%%%%%%%%%%%%%%%
time = now;

figureHandle = figure('NumberTitle','on',...
    'Name','Stick Input',...
    'Color',[0 0 0],'Visible','on');

axesHandle = axes('Parent',figureHandle,...
    'YGrid','on',...
    'YColor',[0.9725 0.9725 0.9725],...
    'XGrid','on',...
    'XColor',[0.9725 0.9725 0.9725],...
    'Color',[0 0 0]);

hold on;

xlim(axesHandle,[-100 5000]);
ylim(axesHandle,[-100 5000]);

xlabel('stick_input_X','FontWeight','bold','FontSize',14,'Color',[1 1 0]);
ylabel('stick_input_Y','FontWeight','bold','FontSize',14,'Color',[1 1 0]);
title('stick input','FontSize',15,'Color',[1 1 0]);

%%%%%%%%%%%%%%%%%%%graph 2%%%%%%%%%%%%%%%%%%%%%
figureHandle2 = figure('NumberTitle','on',...
    'Name','Roll angle',...
    'Color',[0 0 0],'Visible','on');

% Set axes
axesHandle2 = axes('Parent',figureHandle2,...
    'YGrid','on',...
    'YColor',[0.9725 0.9725 0.9725],...
    'XGrid','on',...
    'XColor',[0.9725 0.9725 0.9725],...
    'Color',[0 0 0]);
hold on;


xlabel('No. of samples','FontWeight','bold','FontSize',14,'Color',[1 1 0]);
ylabel('Roll angle','FontWeight','bold','FontSize',14,'Color',[1 1 0]);
title('Roll Angle','FontSize',15,'Color',[1 1 0]);

%%%%%%%%%%%%%%%%%%%graph 3%%%%%%%%%%%%%%%%%%%%%
figureHandle3 = figure('NumberTitle','on',...
    'Name','P gain',...
    'Color',[0 0 0],'Visible','on');

% Set axes
axesHandle3 = axes('Parent',figureHandle3,...
    'YGrid','on',...
    'YColor',[0.9725 0.9725 0.9725],...
    'XGrid','on',...
    'XColor',[0.9725 0.9725 0.9725],...
    'Color',[0 0 0]);
hold on;


xlabel(' ','FontWeight','bold','FontSize',14,'Color',[1 1 0]);
ylabel('P Gain','FontWeight','bold','FontSize',14,'Color',[1 1 0]);
title('P Gain','FontSize',15,'Color',[1 1 0]);

%%%%%%%%%%%%%%%%%%%graph 4%%%%%%%%%%%%%%%%%%%%%
figureHandle4 = figure('NumberTitle','on',...
    'Name','D gain',...
    'Color',[0 0 0],'Visible','on');

% Set axes
axesHandle4 = axes('Parent',figureHandle4,...
    'YGrid','on',...
    'YColor',[0.9725 0.9725 0.9725],...
    'XGrid','on',...
    'XColor',[0.9725 0.9725 0.9725],...
    'Color',[0 0 0]);
hold on;


xlabel(' ','FontWeight','bold','FontSize',14,'Color',[1 1 0]);
ylabel('D Gain','FontWeight','bold','FontSize',14,'Color',[1 1 0]);
title('D Gain','FontSize',15,'Color',[1 1 0]);